format =  """$time $all"""
[character]
success_symbol = '[I ➜](bold yellow)'
error_symbol = '[X ➜](bold red)'
vimcmd_symbol = '[N ➜](bold green)'
vimcmd_visual_symbol = '[V ➜](bold magenta)'
vimcmd_replace_symbol = '[R ➜](bold blue)'
vimcmd_replace_one_symbol = '[R ➜](bold blue)'

[time]
disabled = false
format = '[$time](blue) '
time_format = '%T'

[git_commit]
tag_symbol = " tag "

[git_status]
conflicted = 'conflicted '
up_to_date = 'up to date'
untracked = '[untracked](yellow) '
stashed = '[stashed ](green) '
modified = '[modified ](magenta)'
staged = '[staged\($count\) ](green)'
renamed = 'renamed '
deleted = 'deleted '
ahead = '[ahead\(${count}\)](yellow)'
diverged = 'diverged ahead\(${ahead_count}\) behind \(${behind_count}\)'
behind = 'behind ${count}'
format = '([$all_status$ahead_behind]($style) )'

[git_state]
format = '\($state ( $progress_current of $progress_total)\) '
cherry_pick = '[cherry pick](bold red)'

[git_branch]
symbol = 'branch '
truncation_length = 4
truncation_symbol = ''
ignore_branches = []

[aws]
symbol = "aws "

[azure]
symbol = "az "

[bun]
symbol = "bun "

[c]
symbol = "C "

[cobol]
symbol = "cobol "

[conda]
symbol = "conda "

[crystal]
symbol = "cr "

[cmake]
symbol = "cmake "

[daml]
symbol = "daml "

[dart]
symbol = "dart "

[deno]
symbol = "deno "

[dotnet]
symbol = ".NET "

[directory]
read_only = " ro"

[docker_context]
symbol = "docker "

[elixir]
symbol = "exs "

[elm]
symbol = "elm "

[fennel]
symbol = "fnl "

[fossil_branch]
symbol = "fossil "

[gcloud]
symbol = "gcp "

[golang]
symbol = "go "

[gradle]
symbol = "gradle "

[guix_shell]
symbol = "guix "

[hg_branch]
symbol = "hg "

[java]
symbol = "java "

[julia]
symbol = "jl "

[kotlin]
symbol = "kt "

[lua]
symbol = "lua "

[nodejs]
symbol = "nodejs "

[memory_usage]
symbol = "memory "

[meson]
symbol = "meson "

[nim]
symbol = "nim "

[nix_shell]
symbol = "nix "

[ocaml]
symbol = "ml "

[opa]
symbol = "opa "

[os.symbols]
Alpaquita = "alq "
Alpine = "alp "
Amazon = "amz "
Android = "andr "
Arch = "rch "
Artix = "atx "
CentOS = "cent "
Debian = "deb "
DragonFly = "dfbsd "
Emscripten = "emsc "
EndeavourOS = "ndev "
Fedora = "fed "
FreeBSD = "fbsd "
Garuda = "garu "
Gentoo = "gent "
HardenedBSD = "hbsd "
Illumos = "lum "
Linux = "lnx "
Mabox = "mbox "
Macos = "mac "
Manjaro = "mjo "
Mariner = "mrn "
MidnightBSD = "mid "
Mint = "mint "
NetBSD = "nbsd "
NixOS = "nix "
OpenBSD = "obsd "
OpenCloudOS = "ocos "
openEuler = "oeul "
openSUSE = "osuse "
OracleLinux = "orac "
Pop = "pop "
Raspbian = "rasp "
Redhat = "rhl "
RedHatEnterprise = "rhel "
Redox = "redox "
Solus = "sol "
SUSE = "suse "
Ubuntu = "ubnt "
Unknown = "unk "
Windows = "win "

[package]
symbol = "pkg "

[perl]
symbol = "pl "

[php]
symbol = "php "

[pijul_channel]
symbol = "pijul "

[pulumi]
symbol = "pulumi "

[purescript]
symbol = "purs "

[python]
symbol = "py "

[raku]
symbol = "raku "

[ruby]
symbol = "rb "

[rust]
symbol = "rs "

[scala]
symbol = "scala "

[spack]
symbol = "spack "

[status]
symbol = "[x](bold red) "

[sudo]
symbol = "sudo "

[swift]
symbol = "swift "

[terraform]
symbol = "terraform "

[zig]
symbol = "zig "
